### ISSUE TITLE
Estudo Google Firebase

### ISSUE THREAD

**Issue by alessandrojsouza** [nudes-cnat/lades#3]
Realizar o estudo sobre o banco de dados FireStore com o objetivo de permitir a construção de um banco de dados NoSQL.
O estudo deve esclarecer como criar, consultar, atualizar e excluir dados do banco.
Assim, como, entender a forma de armazenamento  dos dados no FireBase.

Sugestão de material:
- [https://firebase.google.com/docs/firestore?hl=pt-br&authuser=0](https://firebase.google.com/docs/firestore?hl=pt-br&authuser=0)
- [https://youtu.be/RaSImXo73QA](https://youtu.be/RaSImXo73QA)

**Comment by mateusnoites** [comment]
Estudo realizado. Foi feita a integração entre o banco de dados do Google Firebase e uma página HTML simples no repositório https://github.com/mateusnoites/teste-firebase.
